server:
  port: 8080
  servlet:
    context-path: /base/api
    encoding:
      charset: UTF-8
      force: true
      enabled: true

########################################################################################################################
# Spring
# spring.web.resources.add-mappings=false: 스프링이 자동으로 정적 파일을 매핑하는 동작을 막아 성능을 개선하거나, 정적 파일에 대한 접근을 더 세밀하게 제어하기 위한 설정
# spring.config.import: TLO 로그에서 API의 넘버링을 관리하는 설정파일
########################################################################################################################
spring:
  application:
    name: base-project
  config:
    import: classpath:endpoint-function-ids.yml
  profiles:
    active: local
  web:
    resources:
      add-mappings: false

  ######################################################################################################################
  # Spring Data Source
  # datasource.hikari.maximum-pool-size: 동시에 열 수 있는 데이터베이스 커넥션의 최대 개수
  ######################################################################################################################
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      max-lifetime: 3500000 # 3500초
      connection-test-query: SELECT 1
      connection-timeout: 30000

########################################################################################################################
# 서비스 로그 설정
########################################################################################################################
logging:
  config: classpath:/log4j2/log4j2-${spring.profiles.active}.xml

########################################################################################################################
# 암복호화 유틸
# jasypt.encryptor.bean: co.kr.abacus.base.config.JasyptConfig 에서 생성한 bean 이름
########################################################################################################################
jasypt:
  encryptor:
    bean: jasyptEncryptor

########################################################################################################################
# Spring Actuator
# management.endpoints.web.exposure.include: 노출할 엔드포인트 지정 (health,info 등)
# management.endpoints.web.base-path: 액추에이터 엔드포인트의 기본 경로 설정 
# management.endpoint.health.show-details: 상세 헬스 정보 표시 여부 설정
# management.endpoint.info.access: info 엔드포인트 접근 권한 설정
########################################################################################################################
management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    info:
      access: unrestricted