spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
  h2:
    console:
      enabled: true
      path: /h2-console

########################################################################################################################
# Swagger
# springdoc.swagger-ui.csrf.enabled=true: Swagger UI를 통해 API 호출 시 CSRF 토큰을 포함시켜 CSRF 위조 방지 예외 발생하지 않음.
########################################################################################################################
springdoc:
  packages-to-scan: co.kr.abacus.base.api
  default-produces-media-type: application/json;charset=UTF-8
  default-consumes-media-type: application/json;charset=UTF-8
  title: Abacus base project
  version: v0.0.0
  description: 애버포애버
  swagger-ui:
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
    path: /api-docs
    csrf:
      enabled: true
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true

########################################################################################################################
# 통합 통계 로그
# logger.tlo.instance-code=999: 다중화 서버 환경에서 각 서버별 instance 번호를 각 서버의 환경변수로 제어하는데, 그게 미지정된 경우 999로 표현
########################################################################################################################
logger:
  tlo:
    enable: true
    enable-service-log: true
    enable-file-log: false
    service-name: base-project
    instance-name: local
    instance-code: "001"
    base-dir: ./logs/tlo
    interval-minutes: 5
    check-interval-millis: 1000
    use-immediately-write: true

########################################################################################################################
# MyBatis
# mybatis.mapper-locations: MyBatis Mapper XML 파일의 위치를 지정
# mybatis.configuration.map-underscore-to-camel-case: DB 컬럼명의 언더스코어를 자바 카멜케이스로 자동 매핑
# mybatis.configuration.cache-enabled: MyBatis 캐시 사용 여부 설정
# mybatis.configuration.lazy-loading-enabled: 지연 로딩 사용 여부 설정
# mybatis.configuration.aggressive-lazy-loading: 즉시 로딩 사용 여부 설정 (false: 지연 로딩 우선)
# mybatis.configuration.default-fetch-size: 조회 결과를 가져올 때의 기본 페치 크기 설정
# mybatis.configuration.default-statement-timeout: SQL 실행 시 타임아웃 시간(초) 설정
########################################################################################################################
mybatis:
  mapper-locations: classpath:sql/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    default-fetch-size: 100
    default-statement-timeout: 30