spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

########################################################################################################################
# Swagger
# springdoc.swagger-ui.csrf.enabled=true: Swagger UI를 통해 API 호출 시 CSRF 토큰을 포함시켜 CSRF 위조 방지 예외 발생하지 않음.
########################################################################################################################
springdoc:
  packages-to-scan: co.kr.abacus.base.api
  default-produces-media-type: application/json;charset=UTF-8
  default-consumes-media-type: application/json;charset=UTF-8
  title: Abacus base project
  version: v0.0.0
  description: 애버포애버
  cache:
    disabled: true
  swagger-ui:
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
    path: /api-docs
    csrf:
      enabled: true
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  servers:
    - url: http://localhost:8080/base/api
      description: Localhost Server

########################################################################################################################
# 통합 통계 로그
# logger.tlo.instance-code=999: 다중화 서버 환경에서 각 서버별 instance 번호를 각 서버의 환경변수로 제어하는데, 그게 미지정된 경우 999로 표현
########################################################################################################################
logger:
  tlo:
    enable: true
    service-name: base-project
    instance-name: base-project-instance
    instance-code: '999'
    base-dir: ./logs/tlo
    interval-minutes: 5
    check-interval-millis: 1000
    use-immediately-write: false


########################################################################################################################
# LG U+ APIM
# apim.domain-public: apim 공개 서버
# apim.domain-private: apim 비공개 서버
# apim.client-id: 내 APIM 프로젝트에서 조회 가능
# apim.client-secret: 내 APIM 프로젝트에서 조회 가능
# apim.hmac.shared-key: 외부 API에서 APIM Provider 서버에 접근할 때 복호화 키
########################################################################################################################
apim:
  domain-public: "https://dev-openapi-pb.lguplus.co.kr"
  domain-private: "https://dev-openapi-pv.lguplus.co.kr"
  client-id: cliend-id
  client-secret: client-secret
  hmac-shared-key: ENC(N1TFps+HtWB4qkruGGphKgSqMuE3PVHcQ3P7kSphhrk/wFIUMZ09vq064OlE3E6TW4akxkNDwpPLJJegIkXXEFlftcLc3C298qb+FGtLYTj+2G1gW3lbV9/hO/me0T6IXwoxo6NFdjhI8BgB+WTobZHToFK5CRNKVDIsv9AVz3U3TGhgbZKvAEDvhkuC2lVHWsEzUbPUQHl1q3eYjpzUNjKagn0Sf0wyYZFZe/Zhc2M=)



########################################################################################################################
# GCP
# simba-jdbc-url: GCP Simba Library를 사용한 JDBC 커넥션 풀 연결 URL
# impersonator-account-email: 권한을 가장받을 서비스 계정 (깡통 계정)
########################################################################################################################
gcp:
  simba-jdbc-url: jdbc:bigquery://https://www.googleapis.com/bigquery/v2:443;ProjectId=%s;OAuthType=3;OAuthAccessToken=%s
  project-id: your-project-id
  impersonator-account-email: your-impersonator-account-email