server:
  servlet:
    context-path: /base/api

########################################################################################################################
# Spring
# spring.web.resources.add-mappings=false: 스프링이 자동으로 정적 파일을 매핑하는 동작을 막아 성능을 개선하거나, 정적 파일에 대한 접근을 더 세밀하게 제어하기 위한 설정
# spring.config.import: TLO 로그에서 API의 넘버링을 관리하는 설정파일
########################################################################################################################
spring:
  application:
    name: base-project
  config:
    import: classpath:endpoint-function-ids.yml
  profiles:
    active: local
  web:
    resources:
      add-mappings: false

  ######################################################################################################################
  # Spring Data Source
  # datasource.hikari.maximum-pool-size: 동시에 열 수 있는 데이터베이스 커넥션의 최대 개수
  ######################################################################################################################
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      max-lifetime: 3500_000 # 3500초 (GCP 토큰 수명보다 짧게 설정)
      connection-test-query: SELECT 1
      connection-timeout: 30_000

########################################################################################################################
# GCP
# gcp.token-life-time: 서비스 가장 후 발급되는 인증 토큰의 유효 시간
# gcp.scopes: Google Cloud API에 접근하기 위한 권한 범위 (최소 권한 원칙을 준수할 것)
########################################################################################################################
gcp:
  token-life-time: 3600
  scopes:
    - https://www.googleapis.com/auth/bigquery

########################################################################################################################
# LG U+ APIM
########################################################################################################################
apim:
  oauth:
    end-point: /uplus/intuser/oauth2/token # APIM 토큰 발급 Endpoint
    grant-type: client_credentials # APIM 토큰 발급 방식
    scope: CM BL CH SR # 토큰의 유효성 범위를 지정하는 키워드


########################################################################################################################
# 서비스 로그 설정
########################################################################################################################
logging:
  config: classpath:/log4j2/log4j2-${spring.profiles.active}.xml

########################################################################################################################
# 암복호화 유틸
# jasypt.encryptor.bean: co.kr.abacus.base.config.JasyptConfig 에서 생성한 bean 이름
########################################################################################################################
jasypt:
  encryptor:
    bean: jasyptEncryptor