#logging:
#  level:
#    org.springframework: DEBUG
spring:
  config:
    activate:
      on-profile: local

  # H2 데이터베이스 설정
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  packages-to-scan: com.example.tlo.api
  default-produces-media-type: application/json;charset=UTF-8
  default-consumes-media-type: application/json;charset=UTF-8
  title: TLO Sample local api swagger
  version: v1.0.0
  description: LAMO :)
  cache:
    disabled: true
  swagger-ui:
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
    path: /api-docs
    csrf:
      enabled: true
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  servers:
    - url: http://localhost:8080/tlo/api
      description: Localhost Server

logger:
  tlo:
    enable: true
    service-name: tlo-sample-was
    instance-name: tlo-sample
    instance-code: '999'
    base-dir: ./logs/tlo
    interval-minutes: 5
    check-interval-millis: 1000
    use-immediately-write: false


########################################################################################################################
# LG U+ APIM
########################################################################################################################
apim:
  # apim 공개 서버
  domain-public: "https://dev-openapi-pb.lguplus.co.kr"
  # apim 비공개 서버
  domain-private: "https://dev-openapi-pv.lguplus.co.kr"
  # client-id: 내 APIM 프로젝트에서 조회 가능
  client-id: ENC(EHQvhAHs1ehcTjFq/VFZ2KNHWiCLQHBvVpC7/0xsaJ33JPD3sPyv4GjtKmznLcF7u0L/EJkq69E4UQBDTbgw+fcuF2A1Adgh1tntTgYwTQo=)
  # client-secret: 내 APIM 프로젝트에서 조회 가능
  client-secret: ENC(Wa+naDAvGxQxrpnO2NfCKZeWVHOGQ1MG4vLutz7xxVF/TGO6cLaQepMV/tQ66B0b7pPkWAc4poa+pAwNPMC/gWsLc9EY81lCFjA/Xu4Cxu4=)
  hmac:
    # hmac.shared-key: 외부 API에서 APIM Provider 서버에 접근할 때
    shared-key: ENC(N1TFps+HtWB4qkruGGphKgSqMuE3PVHcQ3P7kSphhrk/wFIUMZ09vq064OlE3E6TW4akxkNDwpPLJJegIkXXEFlftcLc3C298qb+FGtLYTj+2G1gW3lbV9/hO/me0T6IXwoxo6NFdjhI8BgB+WTobZHToFK5CRNKVDIsv9AVz3U3TGhgbZKvAEDvhkuC2lVHWsEzUbPUQHl1q3eYjpzUNjKagn0Sf0wyYZFZe/Zhc2M=)