### 1. HAPPY
POST http://localhost:8080/base/api/validator/method-argument-validation
Content-Type: application/json

{
  "gender": "male",
  "genderNumber": 1
}

### 2. EXCEPTION - gender
POST http://localhost:8080/base/api/validator/method-argument-validation
Content-Type: application/json

{
  "gender": "male1",
  "genderNumber": 1
}

### 3. EXCEPTION - genderNumber
POST http://localhost:8080/base/api/validator/method-argument-validation
Content-Type: application/json

{
  "gender": "male",
  "genderNumber": 3
}

### 4. EXCEPTION - gender, genderNumber
POST http://localhost:8080/base/api/validator/method-argument-validation
Content-Type: application/json

{
  "gender": "male1",
  "genderNumber": 3
}

### 5. EXCEPTION - name (빈 문자열)
POST http://localhost:8080/base/api/validator/method-argument-validation
Content-Type: application/json

{
  "name": "",
  "gender": "male",
  "genderNumber": 1
}

### 6. EXCEPTION - name (null)
POST http://localhost:8080/base/api/validator/method-argument-validation
Content-Type: application/json

{
  "gender": "male",
  "genderNumber": 1
}